version: 2

models:
  - name: claims
    access: public
    config:
      contract:
        enforced: true
    description: "Detailed information about insurance claims"
    columns:
      - name: claim_id
        description: "Unique identifier for each claim"
        data_type: varchar
        constraints:
          - type: not_null
          - type: unique
      - name: policy_id
        description: "Identifier of the policy associated with the claim"
        data_type: varchar
        constraints:
          - type: not_null
      - name: claim_date
        description: "Date when the claim was filed"
        data_type: date
      - name: claim_amount
        description: "Amount claimed"
        data_type: number(38,2)
      - name: claim_status
        description: "Current status of the claim"
        data_type: varchar
      - name: claim_type
        description: "Type of claim"
        data_type: varchar
      - name: adjuster_id
        description: "Identifier of the adjuster handling the claim"
        data_type: varchar
      - name: settlement_date
        description: "Date when the claim was settled"
        data_type: date

  - name: monthly_claims
    access: public
    config:
      contract:
        enforced: true
    description: "Monthly summary of claims by claim type"
    columns:
      - name: month
        description: "Month of the summary"
        data_type: date
        constraints:
          - type: not_null
      - name: claim_type
        description: "Type of claim"
        data_type: varchar
      - name: claim_count
        description: "Number of claims in the month for the claim type"
        data_type: number
      - name: total_claim_amount
        description: "Total amount claimed in the month for the claim type"
        data_type: number(38,2)
      - name: avg_claim_amount
        description: "Average amount claimed in the month for the claim type"
        data_type: number(38,2)
      - name: active_adjusters
        description: "Number of unique adjusters handling claims in the month for the claim type"
        data_type: number